### PR TITLE
Prepare SDK release 3.0

### PR DESCRIPTION
**Pull request by payoto**

### CODE REVIEW

**Comment by payoto** [comment]
Test outcome at `/storage/test-reports-2022-11-08-17_36/log_tensorflow2_2022-11-08-17_36/benchmark_results.csv` in Paperspace:

```
"benchmark name"                       ,"Variant name"                         ,"throughput"       ,"latency" ,"total_compiling_time" ,"test_duration" ,"loss" ,"result" ,"cmd"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             ,"env"                                                                                                                                  ,"git_commit_hash"
"Graphcore-Tensorflow2-README_first"   ,"Graphcore-Tensorflow2-README_first"   ,""                 ,""        ,""                     ,"2.660384"      ,""     ,"True"   ,"python3 -m examples_utils.benchmarks.notebook_utils README_first.ipynb ."                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ,"POPLAR_LOG_LEVEL=INFO POPART_LOG_LEVEL=INFO TF_CPP_VMODULE=poplar_compiler=1 "                                                        ,"10f8532e975799199a55dffd51680fbd3066f8e4"
"get-started-run_cluster_gcn_notebook" ,"get-started-run_cluster_gcn_notebook" ,""                 ,""        ,""                     ,"12.934384"     ,""     ,"False"  ,"python3 -m examples_utils.benchmarks.notebook_utils run_cluster_gcn_notebook.ipynb ."                                                                                                                                                                                                                                                                                                                                                                                                                                                            ,"POPLAR_LOG_LEVEL=INFO POPART_LOG_LEVEL=INFO TF_CPP_VMODULE=poplar_compiler=1 "                                                        ,"10f8532e975799199a55dffd51680fbd3066f8e4"
"keras-demo"                           ,"keras-demo"                           ,""                 ,""        ,"280.407761"           ,"287.72982"     ,""     ,"True"   ,"python3 -m examples_utils.benchmarks.notebook_utils demo.ipynb ."                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ,"POPLAR_LOG_LEVEL=INFO POPART_LOG_LEVEL=INFO TF_CPP_VMODULE=poplar_compiler=1 "                                                        ,"10f8532e975799199a55dffd51680fbd3066f8e4"
"mnist-mnist"                          ,"mnist-mnist"                          ,""                 ,""        ,"17.020313"            ,"26.35277"      ,""     ,"True"   ,"python3 -m examples_utils.benchmarks.notebook_utils mnist.ipynb ."                                                                                                                                                                                                                                                                                                                                                                                                                                                                               ,"POPLAR_LOG_LEVEL=INFO POPART_LOG_LEVEL=INFO TF_CPP_VMODULE=poplar_compiler=1 "                                                        ,"10f8532e975799199a55dffd51680fbd3066f8e4"
"tensorboard-demo"                     ,"tensorboard-demo"                     ,""                 ,""        ,"89.619338"            ,"239.962654"    ,""     ,"True"   ,"python3 -m examples_utils.benchmarks.notebook_utils demo.ipynb ."                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ,"POPLAR_LOG_LEVEL=INFO POPART_LOG_LEVEL=INFO TF_CPP_VMODULE=poplar_compiler=1 "                                                        ,"10f8532e975799199a55dffd51680fbd3066f8e4"
"tf2_cluster_gcn_ppi_train_gen_pod4"   ,"tf2_cluster_gcn_ppi_train_gen_pod4"   ,"66410.9797689894" ,""        ,"47.074374"            ,"64.242574"     ,""     ,"True"   ,"poprun --mpi-global-args=--tag-output --num-replicas=4 --num-instances=4 --executable-cache-path=/tmp/tf_cache/ python3 /notebooks/clones/https---github-com-graphcore-examples-git/gnn/cluster_gcn/tensorflow2/run_cluster_gcn.py --training.epochs 40 --training.replicas 4 --training.epochs-per-execution 4 --do-validation false --do-test false --wandb false --dataset-name generated --regenerate-dataset-cache true --save-dataset-cache false --regenerate-clustering-cache true --save-clustering-cache false configs/train_ppi.json" ,"POPLAR_LOG_LEVEL=INFO POPART_LOG_LEVEL=INFO TF_CPP_VMODULE=poplar_compiler=1 TF_POPLAR_FLAGS=--executable_cache_path=/tmp/tf_cache/ " ,"f60a6b32f85e3971679bd086de238d4b04044377"

```

## Failure in the Cluster GCN notebook

```log
INFO:root:Loading raw dataset...
CRITICAL:root:Data ogbn-arxiv is not present at /localdata/paperspace/graph_datasets/.
CRITICAL:root:Please download data using python3 data_utils/dataset_loader.py --dataset-name ogbn-arxiv --data-path /localdata/paperspace/graph_datasets/


/usr/local/lib/python3.8/dist-packages/IPython/core/interactiveshell.py:3351: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)

```

**Comment by rahult-graphcore** [comment]
Commit [0c89710](https://github.com/graphcore/Graphcore-Tensorflow2-fork/pull/3/commits/0c897107ab1d2b62b126d6e61591405ceec59157) contains a patch for the cluster gcn notebook, using yaml: https://github.com/graphcore/paperspace-automation/commit/601d8dd2a1b6c88456e17d64892ede5978a779aa

**Comment by rahult-graphcore** [comment]
Commit https://github.com/graphcore/Graphcore-Tensorflow2-fork/pull/3/commits/04165ee23680392792d582ed9bd7effcbf67a197 adds a missing import, using the yaml: https://github.com/graphcore/paperspace-automation/commit/601d8dd2a1b6c88456e17d64892ede5978a779aa

**Comment by payoto** [comment]
Involving @nmb-paperspace

**Comment by nmb-paperspace** [comment]
Reviewed the commits on this branch similarly to Graphcore-HuggingFace-fork. No direct PR comments.

**Comment by payoto** [comment]
Closing to open the PR into upstream

**Pull request closed without merging**
